# Generated by Django 6.0 on 2025-12-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('message', models.CharField()),
                ('status', models.CharField(choices=[('n', 'new'), ('ip', 'in_progress'), ('c', 'closed')])),
            ],
        ),
    ]
